### ISSUE TITLE
The note color menu

### ISSUE THREAD

**Issue by Luisinhi010** [tposejank/FNF-PsychEngine-ExtraKeys#10]
### Describe your bug here.

the notes color menu doesn't show all 11 notes, I would even make a pull request but I'm not on my computer right now

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I saw this bug in the latest version of gamebanana some time ago, but I forgot to mention

**Comment by tposejank** [comment]
will be fixed later when i have a working computer.

**Comment by Luisinhi010** [comment]
oh

**Comment by CheesecakeForever** [comment]
> will be fixed later when i have a working computer.

ur pc exploded
