### ISSUE TITLE
Is there .FLA for the keys?

### ISSUE THREAD

**Issue by CheesecakeForever** [tposejank/FNF-PsychEngine-ExtraKeys#17]
### Describe your problem here.

The title. Please add it if you can. Thanks in advance.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes source and assets

**Comment by tposejank** [comment]
Hi, this will be added soon. Thanks for telling
