### ISSUE TITLE
controls key keeps reset

### ISSUE THREAD

**Issue by anonybean** [tposejank/FNF-PsychEngine-ExtraKeys#4]
### Describe your bug here.

when i edit my keybind and now close the game and open the game again my key bind keeps starting over

https://user-images.githubusercontent.com/94534428/148585789-1c5e4dd0-cc26-4e75-a24d-7d0874c8e4cb.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by tposejank** [comment]
decompress the game first then try again

**Comment by tposejank** [comment]
make sure you also exit the state after setting your keybind (aka press escape)

**Comment by tposejank** [comment]
for it to save settings

**Comment by anonybean** [comment]
oh ok thx
