### ISSUE TITLE
Mods without mania argument only use one key

### ISSUE THREAD

**Issue by TomyGamy** [tposejank/FNF-PsychEngine-ExtraKeys#9]
### Describe your bug here.

If you use a mod not made for extra keys, the game will use only 1 key. I thik I have a solution :
In Playstate.hx, just before 

> if (mania < Note.minMania || mania > Note.maxMania)
>       mania = Note.defaultMania;

maybe replace

> mania = SONG.mania;

by

> if SONG.mania == null
>       mania = 3;
> else
>       mania = SONG.mania;

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I used the windows build found on GameBanana

**Comment by TomyGamy** [comment]
Or change 

public static var mania:Int = 0;

with

public static var mania:Int = 3;

**Comment by tposejank** [comment]
Solved

**Comment by tposejank** [comment]
nvm

**Comment by BeansCool54** [comment]
lol

**Comment by TomyGamy** [comment]
oh ok
